apiVersion: v1
data:
  password: cG9zdGdyZXNwdw==
  username: bG9ndXNlcg==
kind: Secret
metadata:
  labels:
    application: spilo
    cluster-name: {{ .Values.name }}
    team: {{ .Values.spec.teamId }}
  name: "{{ .Values.spec.databases.logs }}.{{ .Values.name }}.credentials.postgresql.acid.zalan.do"
  namespace: {{ .Release.namespace }}
type: Opaque