apiVersion: v1
data:
  password: cG9zdGdyZXNwdwo=
  username: bG9ndXNlcg==
kind: Secret
metadata:
  creationTimestamp: {{ now | date "2006-01-02T15:04:05Z"}}
  labels:
    application: spilo
    cluster-name: {{ .Values.name }}
    team: {{ .Values.spec.teamId }}
  name: "{{ .Values.spec.databases.logs }}.{{ .Values.name }}.credentials.postgresql.acid.zalan.do"
  namespace: postgres
  uid: {{ uuidv4 }}
type: Opaque